DROP TABLE USER if EXISTS ;
CREATE table USER (
  id bigint generated BY DEFAULT as IDENTITY ,
  username  VARCHAR (40),
  NAME VARCHAR (20),
  age int(3),
  balance DECIMAL (10,2),
  PRIMARY KEY (id)
);