server:
  port: 8761
eureka:
  client:
    serviceUrl:
      # 将自己注册到peer2这个Eureka上面去
      defaultZone: http://localhost:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true