server:
  port: 8001
spring:
  application:
    name: ms-provider-user
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:  #指定数据源
    platform: h2     #指定数据源类型
    schema: classpath:schema.sql    # 指定H2数据库的建表脚本
    data: classpath:data.sql      # 指定H2数据库的数据脚本
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@peer1:8761/eureka/,http://user:password123@peer2:8762/eureka/
#  关闭自我保护  当服务下线时，就down
  server:
    enable-self-preservation: false
  instance:
    perfer-ip-address: true
    # 手动指定服务ip
    ip-address: 127.0.0.1
    metadata-map:
        #自定义元数据  key/value 都可以随便写
        my-metadata: 自定义元数据
