spring:
  application:
    name: ms-discovery-eureka-ha
  profiles:
    active: @profilesActive@

security:
  basic:
    enabled: true   # 开启基于HTTP basic的认证
  user:
    name: user               #配置登录账号
    password: password123    # 配置登录密码
---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  # 指定当peofile=peer1时，主机名是peer1
  instance:
    hostname: peer1
    prefer-ip-address: true
  client:
    serviceUrl:
      # 将自己注册到peer2这个Eureka上面去
      defaultZone: http://peer2:8762/eureka/
    fetch-registry: false
    register-with-eureka: false
---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  # 指定当peofile=peer1时，主机名是peer1
  instance:
    hostname: peer2
    prefer-ip-address: true
  client:
    serviceUrl:
      # 将自己注册到peer2这个Eureka上面去
      defaultZone: http://peer1:8761/eureka/
    register-with-eureka: false
    fetch-registry: false

